# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/dtkgui.spec

# add or remove files that should be synced
synced_files:
    - rpm/dtkgui.spec
    - .packit.yaml

upstream_package_name: dtkgui
# downstream (Fedora) RPM package name
downstream_package_name: dtkgui

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/dtkgui.spec"
